### ISSUE TITLE
[2019B3B] package not complete

### ISSUE THREAD

**Issue by Tenshock** [Tronix117/wik-njs-303-skeleton#1]
The module sqlite doesn't appear in the package.

**Comment by Tronix117** [comment]
C'est résolu, le problème était que le "const db = require('sqlite')" était au mauvais endroit, dans la route au lieu d'être dans le model. On avait été un peu vite. Par ailleurs j'ai rajouté le sqlite au package.json (oubli). Si vous avez une erreur indiquant que sqlite n'existe pas, refaites un `npm install`.

Pour ceux qui ne savent pas faire de merge, regardez simplement les modifications que j'ai apporté en cliquant sur le commit 3dc585f
