### ISSUE TITLE
Execution multiple de promesses

### ISSUE THREAD

**Issue by Tenshock** [Tronix117/wik-njs-303-skeleton#2]
Pour exécuter plusieurs promesses on peut faire
`Promise.all([promise1(params), promise2(params)]).then((result) => { code })`
mais je reçois un array de valeurs et je dois exécuter une promise sur chaque valeurs de ce tableau.
c'est à dire que je dois exécuter `promise(array[0]), promise(array[1]), promise(array[2])…` pour un nombre aléatoire de valeurs
Comment puis-je boucler au sein de mes promises pour obtenir un code harmonieux et efficient niveau gestion d'erreurs ?

**Comment by Tronix117** [comment]
Est-ce que quelque chose comme cela répond à ta question ?

``` es6
var promises = []

promises.push(Promise.resolve(35))
// promises.push(Promise.reject('toto erreur')) // Décommente pour simuler une erreur
promises.push(Promise.resolve('abcd'))

Promise.all(promises).then((results) => {
  results.forEach((result, i) => {
    console.log('Résultat de la promesse numéro ' + i + ' : ', result)
  })
}).catch((err) => {
   console.error('Une des promesses a levé une erreur : ', err)
})
```

**Tip 1:** `Promise.reject` et `Promise.resolve` permettent de générer des promesses déjà résolues ou rejetées avec le résultat en paramètre.

**Tip 2:** `Array.forEach((result, i)=>{})` est moins efficace que `for(i in results)` mais par contre en cas d'utilisation asynchrone à l'intérieur du `for`, on est sûr de toujours avoir accès au bon `i` et `result`.

**Comment by Tenshock** [comment]
C'est parfait

**Comment by Tronix117** [comment]
J'ai rajouté deux tips :)
