### ISSUE TITLE
Option "Voir mes todos / Voir les todos de mon équipe"

### ISSUE THREAD

**Issue by Tenshock** [Tronix117/wik-njs-303-skeleton#3]
Si je comprends bien la consigne l'utilisateur, sur un simple clic peut se voir afficher soit ses todos soit les todos de son équipe. Quelle est la solution à adopter pour obtenir un tel effet ?
Je pensais faire une route pour "mes todos" et une route pour "les todos de mon équipe" mais ce n'est pas réellement une option.
Je ne sais pas quelle est la démarche à suivre d'un point de vu logique, un peu d'aide, une piste ?

**Comment by SombreroElGringo** [comment]
Sinon, dans ton todos/index.pug  tu fais 2 divs un div qui contient uniquement les todos de l'utilisateur et un pour les todos de la team. Ensuite tu ajoutes 2 boutons 'My todos' et 'Teams's todo', puis tu utilises la magie du jQuery pour afficher ou cacher tel ou tel div selon le bouton utiliser par l'user.

**Comment by Tronix117** [comment]
C'est une simple requête filtrée sur ton API REST, donc tu dois avoir un `/todos`, il faudra du coup gérer un `/todos?team=3241`, et ne pas oublier de sécuriser de façon à na pas accéder à des teams auxquelles on a pas accès.

Dans l'idéal il faudrait gérer :
- `/todos?team=3241` => Seulement les todos d'une team 
- `/todos?team=none` => Pas de team associée
- `/todos?assignee=12` ou `/todos?assignee=me` => eventuellement si on veut récupérer les todos qui me sont assignées
- etc...

Tout ce qui est filtre, pagination, tri, etc... qui permettent de modifier le résultat de la requête sur une ressource doivent être passé sur le `req.query` avec le `?a=foo&b=bar`

**Comment by Tronix117** [comment]
@SombreroElGringo Pourquoi pas, mais dans ce cas utiliser de l'Ajax, et modifier l'URL en live. Je tiens à ce que on reste en fonctionnement RESTFull, c'est à dire que si tu donnes l'url de ta page à quelqu'un, il doit avoir exactement le même affichage. Et si tu fais la requête sur cette même URL en `accept: application/json`, tu dois aussi avoir les mêmes données retournées.
