### ISSUE TITLE
Par où commencer ?

### ISSUE THREAD

**Issue by lakfoo** [Tronix117/wik-njs-303-skeleton#4]
Bonjour Jeremy !

Je me lance sur le projet mais je n'ai aucune idée de par où commencer, serait-il possible d'avoir quelques pistes ?
 
Cordialement

 Valentin

**Comment by Tronix117** [comment]
Hey Valentin, désolé je n'ai pas encore eu le temps de te répondre, mais je ne t'oublies pas, tu as pu t'en sortir ?

**Comment by lakfoo** [comment]
Ah ok pas de soucis ! Demain je pense qu'on aura plein de question avec
Malik on va s'y mettre à deux, j'ai déjà commencer à me remettre dans le
squelette afin d'éviter d’être trop perdu mais ça reste compliqué !
